kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: golang
    commands:
      - go build
      - go test

  - name: frontend
    image: golang
    commands:
      - npm install
      - npm test

  - name: build
    image: plugins/slack
    settings:
      channel: general
    depends_on:
      - backend
      - frontend
## 載入 docker config 設定
image_pull_secrets:
  - dockerconfigjson
