kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
  - name: practice-1
    image: golang
    commands:
      - echo hello drone pipeline-01
      - sleep 2

  - name: practice-2
    image: golang
    commands:
      - echo hello drone pipeline-02
      - sleep 10

  - name: practice-3
    image: golang
    commands:
      - echo hello drone pipeline-03
      - sleep 5

---
kind: pipeline
type: docker
name: pipeline-04

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-03

depends_on:
  - pipeline-01

