kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
  - name: practice-1
    image: golang
    commands:
      - echo hello drone pipeline-01
      - sleep 1

  - name: practice-2
    image: golang
    commands:
      - echo hello drone pipeline-02
      - sleep 2

---
kind: pipeline
type: docker
name: pipeline-02

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-03
    agent:
      -runner-frontend

#depends_on:
#  - pipeline-01

---
kind: pipeline
type: docker
name: pipeline-03

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-05
    agent:
      -runner-frontend

---
kind: pipeline
type: docker
name: pipeline-04

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-06
    agent:
      -runner-backend

---
kind: pipeline
type: docker
name: pipeline-05

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-06
    agent:
      -runner-frontend
depends_on:
  - pipeline-01
  - pipeline-02
  - pipeline-03
  - pipeline-04

