kind: pipeline
type: docker
name: pipeline-01

clone:
  disable: true

steps:
  - name: practice-1
    image: golang
    commands:
      - echo hello drone pipeline-01
      - sleep 1

  - name: practice-2
    image: golang
    commands:
      - echo hello drone pipeline-02
      - sleep 1

#  - name: practice-3
#    image: golang
#    commands:
#      - echo hello drone pipeline-02
#      - sleep 1
#
#  - name: practice-4
#    image: golang
#    commands:
#      - echo hello drone pipeline-03
#      - sleep 5
#    depends_on:
#      - practice-3

---
kind: pipeline
type: docker
name: pipeline-04

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-03

#depends_on:
#  - pipeline-01

---
kind: pipeline
type: docker
name: pipeline-05

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-05

---
kind: pipeline
type: docker
name: pipeline-06

clone:
  disable: true

steps:
  - name: practice
    image: golang
    commands:
      - echo hello drone pipeline-06
---
kind: pipeline
type: docker
name: pipeline-python-07

clone:
  disable: true

steps:
  - name: practice
    image: python
    commands:
      - pip install -r requirements.txt
      - pytest


